using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class DoSKiddie : MonoBehaviour
{
    public static string attackName = "DoSing Kiddie"; //Attack name
    public static string attackEffect ="";//The effect on the company
    public static bool attackCountered =false; //If the attack has been countered
    public static string attackCounter = "Office Firewall"; //What counters the attack
    public static string attackCounterEffect = "A sudden surge of traffic is detected: a number of machines from all around the world are trying to flood your office network with requests. Fortunately, your network administrator can quickly update the filtering rules of the offices firewall, and the attack does not cause much disruption.";
    public static int turnCountered; //Will point which turn it got countered
    public static string whatCounter; //Assings the variable to which defence stopped this attack
    


    private void Update()
    {
        if (PlayGameAssets.currentTurn >= 2)
        {
            attackEffect = "The office network is hit with traffic generated by hundreds of infected bots from all around the world. The network is out of order, no one can connect to the Internet, and the local database and server crash. As no employee can work properly for several days, the share price takes a small dip.";
            
        }
    }
}
